language: r
r: bioc-release
bioc_required: true
bioc_use_devel: false

cache:
  apt: true
  packages: true
  timeout: 3000

before_install:
  - sudo apt-get update
  - sudo apt-get install jags

# r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes # --no-manual

#script:
#- travis_wait R CMD build .
#- R CMD check --no-build-vignettes *tar.gz
